### PR TITLE
hacktoberfest

### PR DESCRIPTION
**Pull request by ayaan-qadri**
formatted

### CODE REVIEW

**Comment by Harshal-Vaidya** [comment]
Could you please assign me the issue under hacktober fest I would like to work on it. Thank you

**Comment by johmn123-wq** [comment]
Sir Can I work on this issue if you want.

**Comment by yash-jivani** [comment]
> Could you please assign me the issue under hacktober fest I would like to work on it. Thank you

Brother my project is not participating in hectoburfest.. so even if I assign it to you.  Even then there will be no add in progress.
Try to find a project that will participate in the Hacktober Fest.

**Comment by yash-jivani** [comment]
> Sir Can I work on this issue if you want.

If there has an issue in this code then just let me know. 
Thank you.

**Comment by johmn123-wq** [comment]
Ohk no problem.

**Pull request closed without merging**
